spring:
  thymeleaf:
    cache: true

database:
  host: 192.168.2.107
  port: 3306
  databasename: smartparkportal
  username: root
  password: Shiyi123456

##各个支付产品的支付平台配置
paymentPlatform:
#  online: HELI_PAY     #网银支付 合利宝
#  quickpay: INDUSTRIAL   #快捷支付 合利宝
#  apppay: HELI_PAY     #扫码支付 合利宝
  transfer: HELI_PAY   #代付 兴业银行
  settle: HELI_PAY     #结算 合利宝

heliPay:
  autoTestMerchantCode: E1800333424 #珠海软易公司
  manualTestMerchantCode: E1800332734 #高新区软易软件
  merchantEntryUrl: http://pay.trx.helipay.com/trx/merchantEntry/interface.action
  transferUrl: http://pay.trx.helipay.com/trx/transfer/interface.action
  credentialUploadUrl: http://pay.trx.helipay.com/trx/merchantEntry/upload.action
  appPayUrl: http://pay.trx.helipay.com/trx/app/interface.action
  appPayNotifyUrl: http://${sysDomain}/rest/pay/appPay/appPayNotify
  appPayRefundNotify: http://${sysDomain}/rest/pay/appPay/appPayRefundNotify
  firstClassMerchantNo: C1800215128
  signkeyCommon: Kx7VWd6dr00Ii5eK2IEwzBbnVGw76b0Z  #进件签名密钥
  encryptKeyCommon: 8Z8af7rAWIKSWBgjfjks1N37       #进件加密密钥
  signkeyAppPay: LYaBv4ZPyUBV8S7E2joKPxbtsupY1opd  #扫码签名密钥
  encryptKeyAppPay: 7ANQFChS4e0AYW0MomoNx81b       #扫码加密密钥
  onlinePayUrl: http://pay.trx.helipay.com/trx/online/interface.action
  onlinePayNoticeUrl: http://${sysDomain}/portal/view/pay/online/pay-success.html
  onlinePayCallbackUrl: http://${sysDomain}/rest/pay/onlinePay/callback
  onlinePayServerCallbackUrl: http://${sysDomain}/rest/pay/onlinePay/serverCallback
  onlineRefundServerCallbackUrl: http://${sysDomain}/rest/pay/onlineRefund/serverCallback
  electronicTransactionUrl: http://pay.trx.helipay.com/trx/merchantAgreement/interface.action
  onlinePaySignkey: lOjRlvHSxW5ze9xrEerR3GCq8Csh8BqL
  onlinePayEncryptKey: lwEXJM1uxaCfwYIG0ijKuAGd
  signkeyTransfer: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMgTJ1d5eeWPDbMDJsfZDaE/RoPIar7My5RMcezhzbCNZlNBt4x6MIEL/MHSmyA9If3gC0FX+UDTlxAsArGDDCMPYbQKFEtoquyn9wsAVvqyCpT8p+Ix1DAb9IFXAKyXRmR8ROSIbc4DKg47hJXjYIfu2RB1o4Qn1r6ufdOZMXCjAgMBAAECgYBR4vz8IVzRpr4doVGTA/Q/Jc2vjCycUOeVl8AdCsIL26Ogucns9em6N3TIw3D4Pe0WokcZBG+gp7kxRkIH8zHYwdg45T8Dc6hNooNxgceI87m7fBeRAxaUjUh4rpEqyAOxnDmgqeh3MzP+DQqGUebpUWHnrBwPUWnhVSMxHCDpyQJBAPSFDg8y7xvJ1AP0OUmQ/feL6DIS30PmRFHTIS7QegelNQyLmvoUDLH9K3ql0Z4uwwmay5L1diI16I1iWOJF3DUCQQDRd+dj85yVJi7NvxNJ+vp0W879RSBz06Pi0hMPTvHyNKAV6XnuAmW+v6u423OSQDd6gB9brpDqAYKx8VvukkR3AkEAh99btaRm67kWH/BY2QFBronGx/RmrfNJaXJ5kOr1tEPgG42D24zClTEKNQfpWA3CARdMIehV8aKlC9NncqzBNQJBALa4MVAvIVe5hvpSwzC1jeQScezccAKZi0xAk/+2jbcJ0NtMXuAPl1FdQR5vz9Cz07E4MiJ3lFGMH8W5FMh3LuECQHVSWO9MKaxL0szZN5HBhCq8wGW5nbw6qGKnjen8D9bqfNrDNekevyAzG27WQJ6MrEGNdeZO2L4XhhjNbqi88/Y=
  merchantBalanceQueryUrl: http://pay.trx.helipay.com/trx/merchant/interface.action
  signkeySettlement: zx9tt5RtUwuo3se97z3SfrWlHHDKsHmx
  merchantSettlementUrl: http://transfer.trx.helipay.com/trx/transfer/interface.action
  wechatPublicPayCallbackUrl: http://${sysDomain}/rest/pay/appPay/appPayNotify
  authPayDirs: http://${sysDomain}/newui/#/,http://${sysDomain}/
  merchantChannelName: ZHSY


swiftpass:
  reqUrl: https://pay.swiftpass.cn/pay/gateway #swiftpass request url
  wechatAppId: wx44df4352848fbca4
  billReqUrl: https://download.swiftpass.cn/gateway   #威富通对账单接口请求地址

  wechatPay:
    notifyUrl: http://${sysDomain}/rest/pay/wechatOfficial/payCallback #微信公众号回调
    payNotifyUrl: http://${sysDomain}/rest/pay/wechatPayNotify/appPayNotify #微信支付回调
  aliPay:
    notify_url: http://${sysDomain}/rest/pay/aliPayNotify/appPayNotify

rate:
  swiftpass: 0.0023
  heliPay: 0.0025
